### ISSUE TITLE
Debug Destroying Base gives error

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#769] opened 2019-09-16 02:12 UTC
When destroying the base through debug (ctrl+shift+alt+right-click), an error occurs when I then click on the base icon down in the Base Tab. When opening the base view for an intact base and then exiting, the base icons change as if they were shuffled down, but the last intact base icon is still there, making it a double entry. If I click on the Bases button with the destroyed base selected, the game crashes. I should be able to get a clip for this.

This is using OpenApoc-v0.2.0.2-16-g2f96387e and V7.1 EWM.

[log.txt](https://github.com/OpenApoc/OpenApoc/files/3612899/log.txt)
[save_cityscape.zip](https://github.com/OpenApoc/OpenApoc/files/3612900/save_cityscape.zip)

**Comment by Quickmind01** [comment] 2019-09-23 02:31
https://youtu.be/O8TILRBxBtI

**Comment by emptyVoid** [comment] 2020-05-03 16:29
Cannot reproduce, should be fixed by #814.

**Comment by FilmBoy84** [comment] 2020-05-03 19:26
Closing as requested by emptyVoid
If the problem returns, please create a new issue and reference this as appropriate

**Closed by FilmBoy84** 2020-05-03 19:26 UTC
Labels: !BUG! HIGH PRIORITY
