### ISSUE TITLE
No auto-fire when holding in left or right mouse button on enemy units

### ISSUE THREAD

**Issue by XCOM-HUB** [OpenApoc/OpenApoc#1389] opened 2024-03-29 03:31 UTC
- OS: Windows 11 Pro x64 23H2
 - OpenApoc Version: 0.0.991
 - No Mods

In the original game, clicking on a weapon equipped on your agent and then holding the left mouse button on an enemy unit should result in auto-fire. Holding the right mouse button on an enemy unit without selecting a firearm should also result in auto-fire. You will auto-fire until depleting the agent's Time Units or if you don't have any more ammo.

PS: On the current version of OpenApoc, you have to click several times to fire your weapon several times. Holding down the mouse buttons will not make your agents fire bullets automatically.

**Comment by Kurtsley** [comment] 2024-04-09 04:53
As per #1058 comment, this should also work with vehicles.

**Comment by FilmBoy84** [comment] 2024-04-09 10:22
Closing as a duplicate of #1058

Please continue all further discussion there

**Closed by FilmBoy84** 2024-04-09 10:22 UTC
Labels: Duplicate, Enhancement, Not Yet Implemented, UnitAI / Behaviour, Verified / Replicated, Quality of Life (QoL), Roadmap, Battlescape, Agent Equipment
