### ISSUE TITLE
General Store Space Change inverted when selling

### ISSUE THREAD

**Issue by Quickmind01** [OpenApoc/OpenApoc#665] opened 2019-07-27 13:32 UTC
After the latest change, it appears the percentage available changes inversely to what is actually happening. For instance, I started at 82% available space, but when I sold 80 vortex mines, my space went up to 87%. When I went to the base screen, my percentage available was 77% in the General Stores. When I went back into the sell screen, the percentage was correct at 77%. Please see saved game and test in Base 1. This is after I fixed all of my ammo numbers. This appears to be a minor bug, in my opinion, but can be confusing for a newer player.
[save_Stream Test.zip](https://github.com/OpenApoc/OpenApoc/files/3438196/save_Stream.Test.zip)

**Comment by FilmBoy84** [comment] 2019-07-27 13:55
Confirmed, this does appear to have been introduced recently

Assigning to JonnyH as he knows better than I what has changed

Also may be worth tacking issue #336 (now not just limited to autocannon AP, but HE and some other items also) whilst we're at it

There's a host of equipment errors in OA at the moment relating storage.

**Comment by Quickmind01** [comment] 2019-07-28 20:58
In case you want to see the video for it: https://www.twitch.tv/videos/459284154

**Comment by ayrtondenner** [comment] 2024-04-14 22:40
Just tried to replicate, it seems to be fixed: https://youtu.be/LdLCwBp6Qog

As you can see from this video, selling 80 vortex mine correctly updated storage used space to 77%.

**Closed** 2024-05-21 15:43 UTC
Labels: !BUG! low priority, Code Query, Verified / Replicated, Cityscape, Marketplace  / Economy
