### ISSUE TITLE
Transfer/Hire/Fire of Scientists causing "No agent matching pointer" and "No agent matching ID" Crashes

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#933] opened 2020-08-04 20:36 UTC
[6th Scientist.zip](https://github.com/OpenApoc/OpenApoc/files/5024356/6th.Scientist.zip)

Lots of things were odd, and the results were bizarre.

Fresh game on 2.0.2-316, no saving and loading whatsoever.

![image](https://user-images.githubusercontent.com/46300745/89342078-432e2400-d670-11ea-9b41-39a834ef9af1.png)

In the Hire/Fire page, many of the troops and scientists had empty HP bars. Hired and fired some, ended up with the value for 6 active scientists (538 research) but one of them couldn't be found, which threw me into a loop with this window:

![image](https://user-images.githubusercontent.com/46300745/89342105-4de8b900-d670-11ea-9c30-8d6cd86dfae4.png)

I had to press OK 5-8 times to progress 5 minutes at a time until research came through and auto-paused the game. This is the save provided, paused miraculously between spazzes. Kept going until eventually, it CTD'd.

Tried reloading the save and it gives me an instant CTD with Agent_91 that can't be found, much like vehicle_19.

![image](https://user-images.githubusercontent.com/46300745/89341950-111cc200-d670-11ea-9117-09f14b92041f.png)

![image](https://user-images.githubusercontent.com/46300745/89341903-019d7900-d670-11ea-8504-e985df802dd2.png)

**Comment by JonnyH** [comment] 2020-08-04 20:55
While I haven't reproduced a crash, there seems to be a weird issue where when you fire someone and they're still at the base (IE you fired someone, exited the hire/sack agents screen then go back into it so the city time hasn't progressed at all) it shows the recently fired person as still in your base, but with an empty healthbar, where you can fire them again.

This clearly isn't correct - sacked agents should immediately be removed from the left-hand "hired agents" list - I believe in the OG all sacked agents are immediately available for re-hire too, which also doesn't seem to be working (once the sacked agents leave the base they're removed from both lists, so can't be re-hired)

**Comment by FilmBoy84** [comment] 2023-01-18 22:09
Should be resolved by recent updates to master for new game starts

To resolve the issues already in this save, decompressing the save file and searching the XML files to remove whole references to "AGENT_91"

**Closed by FilmBoy84** 2023-01-18 22:09 UTC
Labels: !BUG! HIGH PRIORITY, Verified / Replicated, Cityscape, Agent ID Error
