### ISSUE TITLE
No Vehicle Matching ID / when entering alien dimension

### ISSUE THREAD

**Issue by pyhton** [OpenApoc/OpenApoc#991] opened 2021-02-09 19:20 UTC
** Reproducible error like #940 , but different **

**Problem:**
An error occurs when entering the alien dimension. Game is blocked by error loop.

**Description:**
After a few days of trial and error and reloading various savegames, the error seems to appear when the alien ships are shot down 4.April in my game (save game attached)

- If I don't shoot any of them down and skip the day, I can enter the alien dimension as normal.
- If I shoot down one of them (tested with shooting down the transporters) I get the error at midnight when I try to enter the alien dimension.
- This is very annoying ofc. I was much further in the game when entering the a.d. and realized it very late.

So it seems it has something to do with shooting down the enemy ships but ofc. I could be wrong.

[Error+Save.zip](https://github.com/OpenApoc/OpenApoc/files/5953782/Error%2BSave.zip)

**Comment by makus82** [comment] 2021-02-09 19:41
Hi and welcome @pyhton and thx for your retailed report =]

**Comment by Kurtsley** [comment] 2023-08-02 06:06
This has been mentioned before, but this issue is caused by projectiles in the alien dimension. The game is checking these projectiles for collisions and not finding the craft they were fired from. This could be tackled a few ways:

- Remove the projectiles when the craft is destroyed
- Remove projectiles from the dimension when the craft leaves
- Try to remove this check and create a LogWarning stating the owner of the projectile no longer exists
- Probably a better way I'm not thinking of

I think the bottom line is the projectiles can't just disappear when the craft that fired them is destroyed.

**Comment by FilmBoy84** [comment] 2023-08-02 09:23
> This has been mentioned before, but this issue is caused by projectiles in the alien dimension. The game is checking these projectiles for collisions and not finding the craft they were fired from. This could be tackled a few ways:
> 
> * Remove the projectiles when the craft is destroyed
> * Remove projectiles from the dimension when the craft leaves
> * Try to remove this check and create a LogWarning stating the owner of the projectile no longer exists
> * Probably a better way I'm not thinking of

I've been doing some playing with this in the OG

One thing I have noticed is that when all X-COM craft leave the alien dimension, it doesn't always switch immediately if projectiles (or crashing UFOs and aircraft) are still present

Instead, it will run the simulation until everything has crashed, collided, or reached it's TTL (Time to Live) value

Only then will it switch

You can test this by entering the alien dimension with a dimension missile weapon, firing it, then leaving, as long as the missile is going to hit something, the simulation continues until it does then there is a switch of dimensions

Similarly, if a UFO is crashing in the dimension, it will come down (and then explode) before the switch of dimensions is performed

I think a clean solution for OpenApoc is therefore to run the simulation until all projectiles and crashes are complete after the X-COM craft leave then switch dimensions. An added QoL feature not in the Original Game would be to put a message on the message ticker explaining what is happening - but this would need the introduction of a new text string

**Comment by FilmBoy84** [comment] 2023-08-06 10:31
This should be resolved by Kurtsley's fix in #1235 
Issue can therefore be closed

**Closed by FilmBoy84** 2023-08-06 10:31 UTC
Labels: !BUG! HIGH PRIORITY, Verified / Replicated, Alien Dimension, Vehicle ID Error
