### ISSUE TITLE
Elerium doesn't get converted into vehicle weapon ammo

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#495] opened 2019-01-21 01:22 UTC
[341 Elerium Not Converted.zip](https://github.com/OpenApoc/OpenApoc/files/2777269/341.Elerium.Not.Converted.zip)

It appears in both the sales list and the soldier equip screens as the same item you loot in a raid, useless, worth 3000$.

https://imgur.com/a/VllD9Ie

**Comment by FilmBoy84** [comment] 2019-01-25 00:05
This is the same in OG
Elerium in the tactical game is recovered as an agent equip-able greenish orb iirc
It sells at a high value offering an alternative to psiclones for post-raid currency mining
The reason in lore for it not being usable in vehicles is that it is not correctly refined

**Comment by FilmBoy84** [comment] 2019-01-25 00:12
I'm going to close this issue as this is not a bug but shows that something that was in OG as a rare item collected in raids or investigations is still recoverable in OpenApoc as it should be :)

**Closed by FilmBoy84** 2019-01-25 00:12 UTC
