### ISSUE TITLE
[BUG] No transportation "hostile organisation" but TransStellar is neutral

### ISSUE THREAD

**Issue by BeornTB** [OpenApoc/OpenApoc#520] opened 2019-02-15 18:29 UTC
Only lifetree is hostile and none of the orders were passed through them. Transfers, Megapol armor, etc need to be manually gathered or transported by tubes.
[377 PublicTransportOnStrike.zip](https://github.com/OpenApoc/OpenApoc/files/2870352/377.PublicTransportOnStrike.zip)

**Comment by BeornTB** [comment] 2019-02-15 18:33
Update: I tried buying out Lifetree and TransStellar, nothing changed. Transportation is incorrectly still blocked.

**Comment by FranciscoDA** [comment] 2019-02-16 06:13
Transtellar has -76.5 relationship with megapol in your save. OpenApoc requires that the ferry organization is not hostile towards the supplier nor the buyer.

**Comment by FilmBoy84** [comment] 2019-02-16 11:03
Closing issue as things are basically working as intended
Why would two hostile orgs work together to fulfill an order for a third party (X-COM)?

**Closed by FilmBoy84** 2019-02-16 11:03 UTC

**Comment by BeornTB** [comment] 2019-02-16 16:53
Gotcha. Seems odd that they would go off on such wrong footing within 3 days.
