### ISSUE TITLE
[CRASH] when start alien invasion mission in building after center camera on it from Message Log (segmentation fault)

### ISSUE THREAD

**Issue by Atrosha** [OpenApoc/OpenApoc#542] opened 2019-03-21 16:38 UTC
When I select "alien spotted" to focus camera view on Megapol building and Valkyria with agents flied into it. After click on icon to start alien invasion mission the game crashes. Sometimes on loading screen.

Video with bug presentation: https://youtube.com/video/OivfcPrhfVE/

Guided by @FranciscoDA I tried to start with args
--Framework.Renderers=GL_2_0 
--Framework.Renderers=GLES_3_0
--Framework.Data.ImageSetCacheSize=10000

Compiled on Linux Mint 19.1 with g++ and clang++
Bug persist with different versions on linux nVIDIA drivers and opensource nouveau driver.

[save_Atrosha Strategy.save.gz](https://github.com/OpenApoc/OpenApoc/files/2993004/save_Atrosha.Strategy.save.gz)

[gdb_output.txt](https://github.com/OpenApoc/OpenApoc/files/2993007/gdb_output.txt)

**Comment by Atrosha** [comment] 2019-03-24 15:24
In result of our prospects with @FranciscoDA we found the origin that causes a crash:
![chat](https://user-images.githubusercontent.com/37053399/54881390-63d15180-4e60-11e9-8616-635860857d9d.png)

I attach full log with Gl debug info:
[debug_stderr_glinfo_output.txt](https://github.com/OpenApoc/OpenApoc/files/3000514/debug_stderr_glinfo_output.txt)

**Comment by Atrosha** [comment] 2019-03-24 17:37
For now to avoid the crash use
`--Game.ASyncLoading=0 --Framework.Data.ImageCacheSize=10000 --Framework.Data.ImageSetCacheSize=10000`
as game parameters.

It causes cache handler do not delete textures.

**Comment by JonnyH** [comment] 2019-03-25 16:13
The root cause of this issue is when a thread other than the "main" renderer thread tries to load an image, it may cause a cached image to be deleted - and if that was used in the renderer it will also destroy the renderer's private data in a thread where the GL context isn't bound, which is undefined (and indeed some drivers crash or abort). This also can cause crashes at exit for a similar reason - where the renderer (and GL context) are destroyed before the last Images are.

The fix for this would be have a threaded renderer, so all the render ops are called from the same thread as the context is bound - I have some prototypes of this hanging around, but never got around to merging - as it happens none of the drivers I happen to use crash - they just spit out a warning and never destroy the texture (effectively leaking)

**Comment by Atrosha** [comment] 2019-03-25 16:18
We can try together.

**Closed** 2019-06-09 22:09 UTC
Labels: Serious Bug! (CTD)
