### ISSUE TITLE
Item fell of the end of the world - Grav lift

### ISSUE THREAD

**Issue by muton-commander** [OpenApoc/OpenApoc#366] opened 2018-04-03 13:06 UTC
I tried this multiple times. When You fire a brainsucker launcher, throw an item in a grav lift or simply put it down there is a error - Item fell of the end of the world

![image](https://user-images.githubusercontent.com/38039785/38251005-7e706a80-3750-11e8-9437-e70b2d8d8cc7.png)

**Comment by FilmBoy84** [comment] 2018-04-04 09:06
Ah, excellent work @muton-commander this appears to be the cause of issue #284 also
I'll reference the post and cause of the bug there too so this bug can be fixed

Thank-you for your assistance

**Comment by BeornTB** [comment] 2019-01-09 21:57
New sighting of the bug in build 336.
[336 lift floor black hole.zip](https://github.com/OpenApoc/OpenApoc/files/2742770/336.lift.floor.black.hole.zip)

https://imgur.com/a/CzJrZYI

No brainsucker launcher on the floor, anthropod died on the bottom floor of the lift.

**Comment by FilmBoy84** [comment] 2019-01-15 13:57
All fixed as of today
Closing

**Closed by FilmBoy84** 2019-01-15 13:57 UTC
