### ISSUE TITLE
Vehicle Inventory Invisible After Y=16

### ISSUE THREAD

**Issue by drages** [OpenApoc/OpenApoc#1034] opened 2021-05-06 08:34 UTC
Hey.

I tried to add engines after Y=14, like:
```
<entry>
					<type>VehicleEngine</type>
					<align_x>Centre</align_x>
					<align_y>Centre</align_y>
					<bounds>
						<p0>
							<x>10</x>
							<y>14</y>
						</p0>
						<p1>
							<x>14</x>
							<y>18</y>
						</p1>
					</bounds>
				</entry>
```
As a result, it worked but in game UI, half of it was invisible.
![4weapon2engine](https://user-images.githubusercontent.com/3720432/117267448-f07fd380-ae5e-11eb-8cf3-ef1e8464d7ed.png)

**Comment by FilmBoy84** [comment] 2021-05-06 11:38
Thanks for report
I suspect this is a .form file error

Your mod may need a new vequipscreen.form under data/forms that increases the boundaries for slots to appear in

Have a play with the form file yourself, if you cannot fix, I'll change the labels to it being a bug with the game

Until then, I'll label this as a modding issue

**Comment by FilmBoy84** [comment] 2021-05-06 12:40
Issue resolved, it was the vequipscreen.form that needed changing for the mod in question
On modifying the Paper Doll size and putting the custom .form file into the mod structure
OpenApoc now shows things as intended

Closing this issue

**Closed by FilmBoy84** 2021-05-06 12:40 UTC
Labels: Graphical User Interface (UI/GUI), Modding
