### ISSUE TITLE
Buying items produces error "Hostile organization refuses to carry out the requested transportation for this company, proceed?"

### ISSUE THREAD

**Issue by dethstryke01** [OpenApoc/OpenApoc#1342] opened 2024-02-15 12:55 UTC
Buying things from organizations listed as non-hostile on the organizations tab produced the error message, "Hostile organization refuses to carry out the requested transportation for this company, proceed?" After pressing yes, the goods purchased were eventually delivered. Buying anything from any organization produced this error, even though none were listed as hostile. This seems to be the same error from issue #843 but in a different situation, because all production buildings on the map are not destroyed.  

https://youtu.be/GFtjx1DuInU?t=1819
https://youtu.be/GFtjx1DuInU?t=2640

[save_after marsec purchase warning.zip](https://github.com/OpenApoc/OpenApoc/files/14296971/save_after.marsec.purchase.warning.zip)
[save_after general metro warning.zip](https://github.com/OpenApoc/OpenApoc/files/14296973/save_after.general.metro.warning.zip)
[settings.zip](https://github.com/OpenApoc/OpenApoc/files/14297125/settings.zip)

Window 10 x64 22H2
OpenApoc version 0.0.930
no mods in use

**Comment by FilmBoy84** [comment] 2024-02-15 18:56
This usually happens when the organisation from which you are buying is hostile to Transtellar

Because they do not get on the order cannot be completed - OpenApoc offers you a means to transport yourself if the option is enabled, but otherwise, in the OG and OpenApoc this is normal behaviour

The main reason it happens so frequently in OpenApoc is the known issue with Org relations lacking a "long term bias" seen in the original game but not yet implemented in OpenApoc - so they flip allegiances on a whim and are very unstable...

In your MarSec save Transtellar is hostile to you so they will not transport goods - this is normal. If you pay them a bribe, they do deliver as they are not hostile with Marsec

The same appears to be the case with your General Metro save - i can bribe transtellar, and i do not get the warning

So, in both cases, the issue is your relation to Transtellar, not the Orgs from which you are buying

I will close this issue for now as it's working as intended and as per the OG...

I have however marked it with a "Better Design Required" tag in case someone can think of a way to further enhance the Original Game feedback

**Closed by FilmBoy84** 2024-02-15 18:56 UTC
Labels: Enhancement, Won't Fix, Quality of Life (QoL), Cityscape, Better Design Required

**Comment by dethstryke01** [comment] 2024-02-15 19:03
Sounds good. It hadn't occurred to me that Transtellar was the one transporting the stuff, but that does make sense.

**Comment by FilmBoy84** [comment] 2024-02-15 19:06
Yeah, in the OG losing Transtellar could cause a game over

Which is why in OpenApoc the optional feature to transport your own stuff (proceed with sale, look for buildings with yellow circle on city map, send vehicle with cargo module repeatedly until yellow circle disappears) was added to compensate for what seems to be a design oversight

Most organisations in the City are tied to something - no all are implemented to control their respective domains yet - but Transtellar and any Production Organisation are fairly critical to the game

**Comment by dethstryke01** [comment] 2024-02-15 20:13
So if the aliens take over Transtellar in the original, you're just totally F'ed?

**Comment by FilmBoy84** [comment] 2024-02-15 20:22
That is correct

If you have rechargable weapons and rely only on alien tech you can still keep going and with luck win

But in essence if you want anything delivered from the city it has to move itself around (vehicles) or be picked up manually (agents) as you will lose access to taxis and people tubes so drag dropping new recruits from their spawn building into an X-COM craft to take home is only way to pick them up

As the saying goes - Welcome to Mega-Primus, whatever you do, don't annoy the taxi drivers... 🤣

**Comment by dethstryke01** [comment] 2024-02-15 20:28
No kidding, I'll try to stay on their good side. I had no idea that level of simulation detail existed in the game, it's pretty amazing.
